### ISSUE TITLE
Recreate 2.x fixtures

### ISSUE THREAD

**Issue by mapsam** [mapbox/mvt-fixtures#15]
Invalid

- [x] **Feature-missing-GeomType.mvt**: The `Feature` message is missing a [`GeomType`](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L41) message.
- [x] **Feature-multiple-geometries.mvt**: The `Feature` message as multiple [`geometry`](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L46) fields encoded, when there should only be one.
- [x] **Feature-no-geometry.mvt**: The `Feature` message has no [`geometry`](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L46).
- [x] **Feature-odd_number_tags.mvt**: Only has a single [`tag`](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L38) where multiples of 2 are required.
- [x] **Feature-unknown_field_type.mvt**: Has a field value of `10`, which is [not listed as an enum](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L8-L13) and therefore invalid. AND **GeomType-type.mvt**: The tag for GeomType is `10`, which is invalid.
- [x] **Key-mistyped_uint32.mvt**: Has a [`key`](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L63) property incorrectly encoded as a type `std::uint32_t`. | n/a
- [x] **Layer-extent-mistyped_string.mvt**: Layer [`extent`](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L70) is incorrectly encoded as a type `std::string`.
- [x] **Layer-extent-none.mvt**: Missing the [`extent`](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L70) type
- [x] **Layer-name-duplicates.mvt**: Includes two layer [`name`](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L57)s with the same value: "layer_name".
- [x] **Layer-name-mistyped_uint32.mvt**: Has a layer name incorrectly encoded as `std::uint32_t`.
- [x] **Layer-name-none.mvt**: Does not include a layer name.
- ~~[ ] **Layer-name-none-version1.mvt**: Same as above, but version 1 tile.~~
- [x] **Layer-no-features.mvt**: Layer has no repeated [`Features`](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L60) tags.
- [x] **Layer-unknow_value_type.mvt**: Includes a Layer value tag of `20`, which is not defined in the spec.
- [x] **Layer-invalid-version.mvt**: Layer version is `99`, which is invalid according to the specification.
- [x] **Layer-version-mistyped_string.mvt**: Layer version is incorrectly typed as a `std::string`.
- [ ] ~~**Layer-version-none.mvt**: Layer does not have a [`version`](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L55) property.~~
- [x] **Tags-nonexistant-values.mvt**: Feature has [`tags`](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L38) that point to non-existent [`Keys`](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L63) and [`Values`](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L66) in the layer.
- [x] **Tile-unknown-tag.mvt**: Tile message has an unknown tag value. The only accepted tag value here is `3`, but this tile encodes a `Feature` with the tag value of `10`.
- [x] **Value-no-fields.mvt**: includes a [`Value`](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L66) without any fields encoded within it.
- [x] **Value-string-mistyped_int64.mvt**: A Layer value property is listed as "string" but encoded as `std::int64_t`.
- [x] **Value-unknown-field-type.mvt**: The [`Value`](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L66) has a field with an [unknown type](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L17-L28).

Valid

- [x] **Feature-single-linestring.mvt**: Single layer with a valid [linestring geometry](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#4353-example-linestring) from the spec docs.
- [x] **Feature-single-multipolygon.mvt**: Single layer with a valid multipolygon geometry
- [x] **Feature-single-multilinestring.mvt**: Single layer with a valid [multilinestring geometry](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#4354-example-multi-linestring) from the spec docs.
- [x] **Feature-single-multipoint.mvt**: Single layer with a valid [multipoint geometry](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#4352-example-multi-point) from the spec docs.
- [x] **Feature-single-point.mvt**: Single layer with a valid [point geometry](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#4351-example-point) from the spec docs.
- [x] **Feature-single-polygon.mvt**: Single layer with a valid [polygon geometry](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#4355-example-polygon) from the spec docs.
- [x] **Feature-unknown-GeomType.mvt**: Single geometry with [`UNKNOWN` type](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L9). This is considered "valid" in the lens of the specification. Encoders/decoders can choose to use or throw on this goemetry type.
- [x] **Value-multiple-fields.mvt**: The [`Value`](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L66) message has two different string entries.
- [x] **Value-single-bool-point.mvt**: Single [Value](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L66) with `bool` type and a single Point feature.
- [x] **Value-single-double-point.mvt**: Single [Value](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L66) with `double` type and a single Point feature.
- [x] **Value-single-float-point.mvt**: Single [Value](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L66) with `float` type and a single Point feature.
- [x] **Value-single-int64-point.mvt**: Single [Value](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L66) with `int64` type and a single Point feature.
- [x] **Value-single-sint64-point.mvt**: Single [Value](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L66) with `sint64` type and a single Point feature.
- [x] **Value-single-string-point.mvt**: Single [Value](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L66) with `string` type and a single Point feature.
- [x] **Value-single-uint64-point.mvt**: Single [Value](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L66) with `uint64` type and a single Point feature.
- [x] **Values-all.mvt**: A buffer with all possible [`Value` types](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L17-L28) encoded in the layer and single Feature.

**Comment by mapsam** [comment]
All fixtures have been created! Waiting on a full release until feedback from @BergWerkGIS via vector-tile-cs and @millzpaugh via vector-tile-js is received and incorporated.
